### ISSUE TITLE
Please adhere to the licence for PyPeri

### ISSUE THREAD

**Issue by takeontom** [peterfdej/record_peri#1]
Hi Peter,

More than happy for you to use PyPeri as you are doing, however could you adhere to its licence please?

In particular, you've copied the main pyperi.py file into your project, but haven't retained the copyright notice and included the MIT licence.

The license for PyPeri is here: https://github.com/takeontom/PyPeri/blob/master/LICENSE

And this site gives a nice summary of the MIT license: https://tldrlegal.com/license/mit-license

It might be easier for you to use pip to install PyPeri from a requirements file, and if there's anything you want to tweak (like the non-existent error handling) then fork PyPeri and change your requirements file to install from that fork.

Sorry to be that guy.

Tom

**Comment by peterfdej** [comment]
np.
Don't use PyPeri anymore.
To many unexpected errors.

Peter.

**Comment by takeontom** [comment]
Ta :+1:
