### ISSUE TITLE
It doesn't stop polling one account even if the scope has ended. 

### ISSUE THREAD

**Issue by sank3th** [peterfdej/record_peri#3]
It keeps saying polling 'accountname' 
And it says no recording file created for 'accountname.mkv'
Great job btw! Please let me know how to resolve this.

**Comment by peterfdej** [comment]
This is sometimes happening when there is a 'Live' scope, but not an actual stream. Normally it will end after a few minutes.
Another option could be a new streaming server, not known by me. You can check using Chrome to watch the stream and look into the developers tools of Chrome, TAB network and mark a playlist.m3u8. You will see in the right window in the request URL the URL of the streaming server.

**Comment by sank3th** [comment]
Hey Peter, thanks for the great work. But isn't this for capturing live scopes too? I tried again, it does the same for live scopes, just keeps polling and then I have to close the window and nothing is captured.
Also is there any place where I can DM you or email you? You're on discord or anything? I've got more doubts.

**Comment by peterfdej** [comment]
Yes, it's for recording live scopes. So, nothing will record? Looks like ffmpeg has no rights writing/creating a file in the folder where you run the python script. What OS are you using?

**Comment by sank3th** [comment]
I'm on Windows 10. I didn't provide any file path myself. How do I do that? That's what I said - it was saying that it kept saying no recording file created for 'accountname'

**Comment by peterfdej** [comment]
Issue can be solved by increasing wait time in 'Start recording for: ' part.
Sometimes it will take a bit longer to start the recording than the default 1 sec. wait time.
